export enum UserStatus {
    PRE_REGISTRATION = 'PRE_REGISTRATION',
    ACTIVE = 'ACTIVE',
    DISABLED = 'DISABLED',
    PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED',
    PASSWORD_MUST_BE_RESETTED = 'PASSWORD_MUST_BE_RESETTED'
  }
  